import { randomUUID } from "node:crypto";
import { parseImportCandidate, type MappingProfile } from "@pwm/contracts";
import { decimalToMinor, parseCsv } from "./canonical-csv-parser";
import type { ParserInput, ParserResult } from "../plugins/parser-plugin";
function parseDate(value: string, format: MappingProfile["dateFormat"]): string { if (format === "yyyy-MM-dd") return value; const [first, second, year] = value.split("/"); if (!first || !second || !year) throw new Error("INVALID_MAPPED_DATE"); return `${year}-${format === "dd/MM/yyyy" ? second : first}-${format === "dd/MM/yyyy" ? first : second}`; }
function parseMinor(value: string, separator: "." | ","): bigint { return decimalToMinor(separator === "," ? value.replace(/\./gu, "").replace(",", ".") : value.replace(/,/gu, "")); }
export class MappedCsvParser {
  constructor(private readonly profile: MappingProfile) {}
  async parse(input: ParserInput): Promise<ParserResult> { input.signal.throwIfAborted(); const columns = this.profile.columns; const candidates = parseCsv(new TextDecoder().decode(input.bytes)).map((row, index) => { const debit = columns.debit ? row[columns.debit] ?? "" : ""; const credit = columns.credit ? row[columns.credit] ?? "" : ""; const raw = columns.amount ? row[columns.amount] ?? "" : debit || credit; const amount = parseMinor(raw, this.profile.decimalSeparator); const direction = debit || amount < 0n ? "debit" : "credit"; const signed = (amount < 0n ? -amount : amount) * (direction === "debit" ? -1n : 1n); const provenance = { source: "row" as const, locator: `row:${index + 2}`, producerId: `mapping:${this.profile.id}`, producerVersion: "1.0.0" }; const balance = columns.balance === undefined ? "" : row[columns.balance] ?? ""; return parseImportCandidate({ schemaVersion: 1, rawRecordId: randomUUID(), transactionDate: { value: parseDate(row[columns.date] ?? "", this.profile.dateFormat), confidence: 1, provenance }, description: { value: row[columns.description] ?? "", confidence: 1, provenance }, amountMinor: { value: signed.toString(), confidence: 1, provenance }, currency: { value: (row[columns.currency] ?? "").toUpperCase(), confidence: 1, provenance }, direction: { value: direction, confidence: 1, provenance }, ...(balance ? { balanceMinor: { value: parseMinor(balance, this.profile.decimalSeparator).toString(), confidence: 1, provenance } } : {}) }); }); return { candidates, warnings: [] }; }
}
